---
title: "Homework 3"
author: "Sarahy Martinez"
date: "10/13/2023"
output: github_document
---

```{r}
library(tidyverse)
library(ggridges)
library(hexbin)
library(patchwork)


```


## Problem 1 

```{r problem 1, eval=FALSE}
library(p8105.datasets)
data("ny_noaa")
```



## Problem 2 

Reading In, Cleaning, Combining Data 
```{r}

#reading in data and cleaning 
accelerometer_data = read_csv(file = "./data/nhanes_accel.csv", na = c("", "NA", 999)) %>%
  janitor::clean_names() %>%
  mutate(seqn=as.character(seqn)) %>% 
  drop_na()


demographics_data = read_csv(file = "./data/nhanes_covar.csv",na = c("", "NA", 999),
                    skip = 4, col_names =TRUE) %>% 
                    janitor::clean_names() %>% 
                     mutate(seqn=as.character(seqn)) %>% 
                    filter(age >=21) %>% 
                    drop_na()

combined_nhanes = 
  left_join(accelerometer_data, demographics_data, by= "seqn") %>% 
  janitor::clean_names() %>%
  relocate(seqn,sex,age,bmi,education) %>% 
  drop_na(sex,age,bmi,education)

```

Producing reader friendly table for number of men and women in each education category 

```{r}
combined_nhanes %>% 
            group_by(sex,education) %>% 
            summarize(counts= n()) %>% 
          mutate(sex = recode(sex, "1"= "male", "2"= "female")) %>% 
          mutate(education=recode(education,
                                  "1"="Less than High School", 
                                  "2"="High School Equivalent", 
                                  "3"="More than high school")) %>% 
            pivot_wider(
              names_from = education,
              values_from = counts,
              names_prefix = "Education "
            ) %>% 
  knitr::kable()
        

```

Age Distributions of each category
```{r}

 demo_data= combined_nhanes %>% 
  mutate(sex = recode(sex, "1" = "male", "2" = "female")) %>% 
  mutate(sex= as.factor(sex)) %>% 
  mutate(education = recode(education,
                            "1" = "Less than High School", 
                            "2" = "High School Equivalent", 
                            "3" = "More than High School")) %>% 
  mutate(education= fct_relevel(education, "Less than High School", "High School Equivalent", "More than High School")) %>% 
  select(age,sex,education) %>% 
  filter(age>=21) %>% 
  drop_na()


ggplot(demo_data, aes(x = age, fill = sex)) + 
  geom_density(alpha = 0.5) + 
  facet_grid(. ~ education) +
  theme_minimal()


```
Aggregating Across Minutes to Create Total Activity 

```{r}

```

